name: baby_package
description: Your package description
version: 0.0.1
homepage: https://github.com/anshra1/baby_package
repository: https://github.com/anshra1/baby_package
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  logger: ^2.4.0
  stack_trace: ^1.12.0
